sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
cache:
  directories:
    - node_modules
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
script: npm run migrate; npm run test
