version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - 80:80
    volumes:
      - ./service/nginx/conf.d:/etc/nginx/conf.d
      - ./service/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./log/nginx:/var/log/nginx
    depends_on:
      - app
    restart: always
    environment:
      TZ: Asia/Tokyo

  redis:
    image: redis:latest
    container_name: 'db-redis'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - ./data/redis:/data
    networks:
      - myapp
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  mysql:
    image: mysql:5.7
    container_name: 'db-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: iD0ntKn0w
      TZ: 'Azia/Tokyo'
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - ./service/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql:/var/lib/mysql
    networks:
      - myapp

  mongodb:
    image: mongo:latest
    container_name: 'db-mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: iD0ntKn0w
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - ./data/mongo:/data/db
    networks:
      - myapp

networks:
  myapp:
    driver: bridge
